version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./index.html:/app/index.html 